RED = '\033[91m'
CYAN = '\033[96m'
GREEN = '\033[92m'
ENDC = '\033[0m'

GAME_FILE_PATTERN = r'^(\w+).txt$'
TEST_FILE_PATTERN = r'^(\w+)_state.txt$'

ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
WORD_PATTERN = r"^[A-Z]+$"
PLAYER_TILES_PATTERN = r"^[A-Z*]{1,7}$"
MAX_PLAYER_TILES = 7
MAX_LENGTH_WORD_SCORE = 50

MAX_SOLUTIONS_TO_SHOW = 5

# Used by the position hashing function.
MAX_BOARD_SIZE = 15
