RED = '\033[91m'
ENDC = '\033[0m'

GAME_FILE_PATTERN = r'^(\w+)_\d{8}_\d{6}\.txt$'

ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
MAX_PLAYER_TILES = 7
MAX_LENGTH_WORD_SCORE = 50

MAX_SOLUTIONS_TO_SHOW = 5

# Used by the position hashing function.
MAX_BOARD_SIZE = 10000
